import oracledb

print("=" * 80)
print("Criando tabelas complementares")
print("=" * 80)

try:
    connection = oracledb.connect(
        user="system",
        password="K1lstrik098!",
        dsn="localhost:1521/XEPDB1"
    )
    
    cursor = connection.cursor()
    
    # 1. LOCATIONS
    print("\n📍 Criando tabela LOCATIONS...")
    try:
        cursor.execute("""
            CREATE TABLE LOCATIONS (
                ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                NAME VARCHAR2(100) NOT NULL,
                LATITUDE NUMBER(9,6) NOT NULL,
                LONGITUDE NUMBER(9,6) NOT NULL,
                PLATFORM_TYPE VARCHAR2(50),
                CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)
        print("✅ LOCATIONS criada")
    except Exception as e:
        if "ORA-00955" in str(e):
            print("⚠️  LOCATIONS já existe")
        else:
            raise
    
    # 2. WEATHER_PROCESSED
    print("🧠 Criando tabela WEATHER_PROCESSED...")
    try:
        cursor.execute("""
            CREATE TABLE WEATHER_PROCESSED (
                ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                LOCATION_ID NUMBER NOT NULL,
                DATA_TIMESTAMP TIMESTAMP NOT NULL,
                IEA_SCORE NUMBER(5,2),
                OPERATIONAL_STATUS VARCHAR2(20),
                INTERRUPTION_PROBABILITY NUMBER(5,2),
                TREND_INDICATOR VARCHAR2(20),
                CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT FK_WEATHER_PROC_LOCATION FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(ID)
            )
        """)
        print("✅ WEATHER_PROCESSED criada")
    except Exception as e:
        if "ORA-00955" in str(e):
            print("⚠️  WEATHER_PROCESSED já existe")
        else:
            raise
    
    # 3. OPERATION_LIMITS
    print("⚙️  Criando tabela OPERATION_LIMITS...")
    try:
        cursor.execute("""
            CREATE TABLE OPERATION_LIMITS (
                ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                OPERATION_TYPE VARCHAR2(100) NOT NULL,
                MAX_WIND NUMBER(6,2),
                MAX_WAVE NUMBER(6,2),
                MAX_CURRENT NUMBER(6,2),
                CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)
        print("✅ OPERATION_LIMITS criada")
    except Exception as e:
        if "ORA-00955" in str(e):
            print("⚠️  OPERATION_LIMITS já existe")
        else:
            raise
    
    # 4. INCIDENTS
    print("⚠️  Criando tabela INCIDENTS...")
    try:
        cursor.execute("""
            CREATE TABLE INCIDENTS (
                ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                LOCATION_ID NUMBER NOT NULL,
                OPERATION_TYPE VARCHAR2(100),
                INCIDENT_TIMESTAMP TIMESTAMP NOT NULL,
                DESCRIPTION VARCHAR2(500),
                SEVERITY VARCHAR2(20),
                CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)
        print("✅ INCIDENTS criada")
    except Exception as e:
        if "ORA-00955" in str(e):
            print("⚠️  INCIDENTS já existe")
        else:
            raise
    
    # 5. Criar/atualizar FK em WEATHER_RAW se necessário
    print("\n✏️  Atualizando WEATHER_RAW com FK em LOCATION_ID...")
    try:
        cursor.execute("""
            ALTER TABLE WEATHER_RAW
            ADD CONSTRAINT FK_WEATHER_RAW_LOCATION 
            FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(ID)
        """)
        print("✅ FK adicionada")
    except Exception as e:
        if "ORA-02260" in str(e):
            print("⚠️  FK já existe")
        else:
            print(f"⚠️  {str(e)}")
    
    # 6. Inserir dados iniciais
    print("\n📝 Inserindo dados iniciais em LOCATIONS...")
    cursor.execute("SELECT COUNT(*) FROM LOCATIONS")
    if cursor.fetchone()[0] == 0:
        cursor.execute("""
            INSERT INTO LOCATIONS (NAME, LATITUDE, LONGITUDE, PLATFORM_TYPE)
            VALUES ('Plataforma Alpha', -12.345678, -38.456789, 'Offshore Oil')
        """)
        cursor.execute("""
            INSERT INTO LOCATIONS (NAME, LATITUDE, LONGITUDE, PLATFORM_TYPE)
            VALUES ('Plataforma Beta', -11.0325631, -37.0829041, 'Offshore Oil')
        """)
        print("✅ Localizações inseridas")
    else:
        print("⚠️  LOCATIONS já tem dados")
    
    cursor.execute("SELECT COUNT(*) FROM OPERATION_LIMITS")
    if cursor.fetchone()[0] == 0:
        cursor.execute("""
            INSERT INTO OPERATION_LIMITS (OPERATION_TYPE, MAX_WIND, MAX_WAVE, MAX_CURRENT)
            VALUES ('Lançamento de ROV', 25, 1.8, 2.0)
        """)
        cursor.execute("""
            INSERT INTO OPERATION_LIMITS (OPERATION_TYPE, MAX_WIND, MAX_WAVE, MAX_CURRENT)
            VALUES ('Helicóptero', 40, 2.5, 3.0)
        """)
        print("✅ Limites operacionais inseridos")
    else:
        print("⚠️  OPERATION_LIMITS já tem dados")
    
    # 7. Criar view operacional
    print("\n👁️  Criando VIEW V_OPERATIONAL_STATUS...")
    try:
        cursor.execute("DROP VIEW V_OPERATIONAL_STATUS")
    except:
        pass
    
    cursor.execute("""
        CREATE VIEW V_OPERATIONAL_STATUS AS
        SELECT 
            L.ID as LOCATION_ID,
            L.NAME,
            L.PLATFORM_TYPE,
            P.DATA_TIMESTAMP,
            P.IEA_SCORE,
            P.OPERATIONAL_STATUS,
            P.INTERRUPTION_PROBABILITY,
            P.TREND_INDICATOR
        FROM WEATHER_PROCESSED P
        JOIN LOCATIONS L ON L.ID = P.LOCATION_ID
        ORDER BY P.DATA_TIMESTAMP DESC
    """)
    print("✅ VIEW criada")
    
    connection.commit()
    
    cursor.close()
    connection.close()
    
    print("\n" + "=" * 80)
    print("✅ TABELAS CRIADAS COM SUCESSO!")
    print("=" * 80)
    
except Exception as e:
    print(f"\n❌ ERRO: {type(e).__name__}")
    print(f"   {str(e)}")
