-- Script de inicialização do banco de dados para MDE
-- Criar tabela WEATHER_RAW

CREATE TABLE WEATHER_RAW (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    LOCATION_ID NUMBER NOT NULL,
    DATA_TIMESTAMP TIMESTAMP NOT NULL,
    WIND_SPEED NUMBER,
    WIND_DIRECTION NUMBER,
    WAVE_HEIGHT NUMBER,
    PRESSURE NUMBER,
    SEA_TEMP NUMBER,
    CURRENT_SPEED NUMBER,
    CREATED_AT TIMESTAMP DEFAULT SYSDATE
);

-- Criar índice para melhorar queries por LOCATION_ID e DATA_TIMESTAMP
CREATE INDEX IDX_WEATHER_RAW_LOCATION DATE ON WEATHER_RAW(LOCATION_ID, DATA_TIMESTAMP);

COMMIT;

-- Verificar se a tabela foi criada
SELECT * FROM USER_TABLES WHERE TABLE_NAME = 'WEATHER_RAW';
